# Generated by Django 5.0.6 on 2024-05-08 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LicensePlate",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=200)),
                ("image", models.ImageField(upload_to="uploads/")),
                ("number", models.IntegerField()),
                ("annotations", models.FileField(upload_to="uploads/")),
            ],
        ),
    ]
