apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-media
  namespace: lpdet
spec:
  capacity:
    storage: 512Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: minikube-storage
  hostPath:
    path: /data/pv-media
