apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-pgdb
  namespace: lpdet
spec:
  storageClassName: minikube-storage
  resources:
    requests:
      storage: 256Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
