apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-models
  namespace: lpdet
spec:
  storageClassName: minikube-storage
  resources:
    requests:
      storage: 1024Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
